name: ffi_tool
version: 0.2.0
description: Generates 'dart:ffi' bindings for C and Objective-C libraries.
homepage: https://github.com/dart-interop/ffi_tool

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  meta: ^1.1.0

dev_dependencies:
  ffi: ^0.1.3
  pedantic: ^1.8.0
  test: ^1.6.0