name: ffi_tool
version: 0.3.0
description: A tool for generating 'dart:ffi' bindings for C and Objective-C libraries.
homepage: https://github.com/dart-interop/ffi_tool

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  meta: ^1.1.0
  ffi: ^0.1.3

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.6.0
